<x-filament-panels::page>
    @php($customers = $this->getCustomers())
    <div class="space-y-6">
        <form wire:submit="getCustomers" class="rounded-2xl border border-white/10 bg-gray-900/70 p-5"><div class="mb-3 text-xs font-semibold uppercase tracking-widest text-gray-400">Filter customers</div><div class="grid gap-4 md:grid-cols-2"><label class="text-sm text-gray-400">From<input type="date" wire:model.live="from" class="mt-1 block w-full rounded-lg border-gray-700 bg-gray-800 text-white"></label><label class="text-sm text-gray-400">Until<input type="date" wire:model.live="until" class="mt-1 block w-full rounded-lg border-gray-700 bg-gray-800 text-white"></label></div></form>
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 class="text-2xl font-semibold text-white">Customers</h2><div class="mt-1 text-sm text-gray-400">{{ \Carbon\Carbon::parse($from)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($until)->format('M d, Y') }}</div></div><div class="flex gap-2"><x-filament::button wire:click="export" icon="heroicon-o-arrow-down-tray" size="sm">Export CSV</x-filament::button><a href="{{ route('admin.customers.pdf', ['from' => $from, 'until' => $until]) }}" class="fi-btn fi-btn-size-sm fi-color-gray inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold"><x-filament::icon icon="heroicon-o-document-arrow-down" class="h-5 w-5" />Export PDF</a></div></div>
        <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-white/10 bg-gray-900/70 p-5"><div class="text-sm text-gray-400">Customers</div><div class="mt-3 text-2xl font-semibold text-white">{{ $customers->count() }}</div></div><div class="rounded-2xl border border-white/10 bg-gray-900/70 p-5"><div class="text-sm text-gray-400">Orders represented</div><div class="mt-3 text-2xl font-semibold text-white">{{ $customers->sum('orders') }}</div></div><div class="rounded-2xl border border-white/10 bg-gray-900/70 p-5"><div class="text-sm text-gray-400">Total customer spend</div><div class="mt-3 text-2xl font-semibold text-emerald-300">${{ number_format($customers->sum('total'), 2) }}</div></div></div>
        <div class="overflow-x-auto rounded-2xl border border-white/10 bg-gray-900/70 p-5"><table class="w-full min-w-[900px] text-sm"><thead><tr class="border-b border-white/10 text-left text-xs uppercase tracking-wider text-gray-500"><th class="px-4 py-3">Customer</th><th class="px-4 py-3">Contact</th><th class="px-4 py-3">Location</th><th class="px-4 py-3 text-right">Orders</th><th class="px-4 py-3 text-right">Total spent</th><th class="px-4 py-3">Last order</th></tr></thead><tbody>@forelse($customers as $customer)<tr class="border-b border-white/5"><td class="px-4 py-4 font-medium text-white">{{ $customer['name'] }}</td><td class="px-4 py-4 text-gray-400">{{ $customer['phone'] }}<br>{{ $customer['email'] ?: 'No email' }}</td><td class="px-4 py-4 text-gray-400">{{ $customer['city'] }}<br>{{ $customer['address'] }}</td><td class="px-4 py-4 text-right text-gray-300">{{ $customer['orders'] }}</td><td class="px-4 py-4 text-right font-semibold text-emerald-300">${{ number_format($customer['total'], 2) }}</td><td class="px-4 py-4 text-gray-400">{{ $customer['last_order']?->format('M d, Y') }}</td></tr>@empty<tr><td colspan="6" class="p-12 text-center text-gray-400">No customers found.</td></tr>@endforelse</tbody></table></div>
    </div>
</x-filament-panels::page>
