<x-filament-panels::page>
    @php($from = $this->from)
    @php($until = $this->until)
    @php($currency = $this->currency)
    @php($report = $this->getReport())
    @php($currencyLabel = $currency === 'all' ? 'All currencies' : $currency)
    <div class="report-shell space-y-6">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 class="text-2xl font-semibold text-white">Profit &amp; Loss</h2><div class="mt-1 text-sm text-gray-400">{{ \Carbon\Carbon::parse($from)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($until)->format('M d, Y') }} · {{ $currencyLabel }}</div></div><div class="flex gap-2"><x-filament::button wire:click="export" icon="heroicon-o-arrow-down-tray" size="sm">Export CSV</x-filament::button><a href="{{ route('admin.profit-loss.pdf', ['from' => $from, 'until' => $until, 'currency' => $currency]) }}" class="fi-btn fi-btn-size-sm fi-color-gray inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold"><x-filament::icon icon="heroicon-o-document-arrow-down" class="h-5 w-5" />Export PDF</a></div></div>

        <form wire:submit="getReport" class="report-filters rounded-2xl p-4 sm:p-5"><div class="mb-3 text-xs font-semibold uppercase tracking-widest text-gray-400">Filter report</div><div class="grid gap-4 md:grid-cols-3"><label class="text-sm text-gray-400">From<input type="date" wire:model.live="from" class="mt-1 block w-full rounded-lg border-gray-700 bg-gray-800 text-white"></label><label class="text-sm text-gray-400">Until<input type="date" wire:model.live="until" class="mt-1 block w-full rounded-lg border-gray-700 bg-gray-800 text-white"></label><label class="text-sm text-gray-400">Currency<select wire:model.live="currency" class="mt-1 block w-full rounded-lg border-gray-700 bg-gray-800 text-white"><option value="all">All currencies</option><option value="USD">USD</option><option value="LBP">LBP</option></select></label></div></form>

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            @foreach ([['Revenue', $report['revenue'], 'heroicon-o-arrow-trending-up', 'text-sky-300'], ['Cost of goods sold', $report['cost'], 'heroicon-o-receipt-percent', 'text-orange-300'], ['Gross profit', $report['profit'], 'heroicon-o-banknotes', 'text-emerald-300'], ['Margin', number_format($report['margin'], 2).'%', 'heroicon-o-chart-pie', 'text-violet-300']] as [$label, $value, $icon, $color])
                <div class="report-card rounded-2xl p-5"><div class="flex items-center justify-between"><span class="text-sm text-gray-400">{{ $label }}</span><x-filament::icon :icon="$icon" class="h-5 w-5 {{ $color }}" /></div><div class="mt-4 text-2xl font-semibold tracking-tight text-white">{{ $label === 'Margin' ? $value : '$'.number_format($value, 2) }}</div>@if ($label === 'Gross profit')<div class="mt-2 text-xs text-emerald-300/80">Net earnings after product costs</div>@endif</div>
            @endforeach
        </div>

        <section class="report-card rounded-2xl p-5 sm:p-6"><div class="mb-5 flex items-end justify-between gap-4"><div><h3 class="text-lg font-semibold text-white">Product performance</h3><p class="mt-1 text-sm text-gray-400">Delivered sales grouped by product and variant</p></div><div class="text-right text-xs text-gray-500">{{ count($report['items']) }} {{ count($report['items']) === 1 ? 'line item' : 'line items' }}</div></div><div class="overflow-x-auto"><table class="w-full min-w-[680px] text-sm"><thead><tr class="border-b border-white/10 text-left text-xs uppercase tracking-wider text-gray-500"><th class="px-4 py-3 font-medium">Product</th><th class="px-4 py-3 font-medium">Variant</th><th class="px-4 py-3 text-right font-medium">Qty</th><th class="px-4 py-3 text-right font-medium">Revenue</th><th class="px-4 py-3 text-right font-medium">Cost</th><th class="px-4 py-3 text-right font-medium">Profit</th></tr></thead><tbody>@forelse ($report['items'] as $item)<tr class="report-row border-b border-white/5"><td class="px-4 py-4 font-medium text-white">{{ $item['product_name'] }}</td><td class="px-4 py-4 text-gray-400">{{ $item['variant_label'] }}</td><td class="px-4 py-4 text-right text-gray-300">{{ $item['quantity'] }}</td><td class="px-4 py-4 text-right text-gray-300">${{ number_format($item['revenue'], 2) }}</td><td class="px-4 py-4 text-right text-gray-400">${{ number_format($item['cost'], 2) }}</td><td class="px-4 py-4 text-right font-semibold text-emerald-300">${{ number_format($item['profit'], 2) }}</td></tr>@empty<tr><td colspan="6" class="p-12 text-center text-gray-400">No delivered sales in this period.</td></tr>@endforelse</tbody><tfoot><tr class="text-white"><td colspan="3" class="px-4 py-4 text-xs font-semibold uppercase tracking-wider text-gray-400">Total</td><td class="px-4 py-4 text-right font-semibold">${{ number_format($report['revenue'], 2) }}</td><td class="px-4 py-4 text-right font-semibold">${{ number_format($report['cost'], 2) }}</td><td class="px-4 py-4 text-right font-semibold text-emerald-300">${{ number_format($report['profit'], 2) }}</td></tr></tfoot></table></div></section>
    </div>
    <style>
        .report-shell form { display:block; margin-bottom:16px; padding:20px; background:#18181b; border:1px solid #2f3035; border-radius:14px; }
        .report-shell form > div:last-child { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:16px; }
        .report-shell label { display:block; color:#a1a1aa; }
        .report-shell input,.report-shell select { display:block; width:100%; margin-top:6px; padding:9px 11px; border:1px solid #3f4148; border-radius:8px; background:#202126; color:#fff; }
        .report-shell > div:nth-child(3) { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:16px; margin-bottom:16px; }
        .report-shell > div:nth-child(3) > div { background:#18181b; border:1px solid #2f3035; border-radius:12px; padding:18px; }
        .report-shell > section:last-of-type { background:#18181b; border:1px solid #2f3035; border-radius:14px; padding:20px; }
        .report-shell table { width:100%; min-width:680px; border-collapse:collapse; }
        .report-shell th { padding:13px 16px; background:#25262a; color:#f4f4f5; text-align:left; font-size:12px; white-space:nowrap; }
        .report-shell td { padding:14px 16px; border-top:1px solid #2f3035; color:#d4d4d8; }
        .report-shell th:nth-child(n+3),.report-shell td:nth-child(n+3) { text-align:right; }
        .report-shell td:first-child { color:#fff; font-weight:600; }
        .report-shell tfoot td { background:#202126; font-weight:700; }
        @media(max-width:700px){.report-shell form > div:last-child,.report-shell > div:nth-child(3){grid-template-columns:1fr}.report-shell .flex{flex-wrap:wrap}}
        .report-hero { background: radial-gradient(circle at 90% 10%, rgba(245,183,72,.2), transparent 35%), linear-gradient(135deg,#172554 0%,#312e81 48%,#111827 100%); position:relative; } .report-hero::after { content:''; position:absolute; inset:auto -5% -65% 45%; height:18rem; border:1px solid rgba(255,255,255,.08); border-radius:999px; transform:rotate(-18deg); } .report-card,.report-filters { background:rgba(17,24,39,.72); border:1px solid rgba(255,255,255,.08); box-shadow:0 12px 35px rgba(0,0,0,.12); } .report-row { transition:background .2s ease; } .report-row:hover { background:rgba(255,255,255,.035); }
        @media print { .fi-sidebar,.fi-topbar,.fi-header,.report-filters,button,[role="button"] { display:none!important; } .fi-main,.fi-page { padding:0!important; } .report-card,.report-hero { box-shadow:none; } }
    </style>
</x-filament-panels::page>
